Software Technologies/C#/ToDoList/TeisterMask/Models/Task.cs
using System.ComponentModel.DataAnnotations;

namespace TeisterMask.Models
{
    public class Task
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Status { get; set; }
    }
}

Software Technologies/C#/ToDoList/TeisterMask/Models/TeisterMaskDbContext.cs
using System.Data.Entity;

namespace TeisterMask.Models
{
    public class TeisterMaskDbContext : DbContext
    {
        public virtual IDbSet<Task> Tasks { get; set; }

        public TeisterMaskDbContext() : base("TeisterMask")
        {
        }
    }
}

Software Technologies/C#/ToDoList/TeisterMask/Controllers/TaskController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using TeisterMask.Models;

namespace TeisterMask.Controllers
{
        [ValidateInput(false)]
	public class TaskController : Controller
	{
	    [HttpGet]
            [Route("")]
	    public ActionResult Index()
	    {
            using(var database = new TeisterMaskDbContext()){
                var task = database.Tasks.ToList();
                return View(task);
            }
            
		}

        [HttpGet]
        [Route("create")]
        public ActionResult Create()
		{

            return View();
        }

		[HttpPost]
		[Route("create")]
        [ValidateAntiForgeryToken]
		public ActionResult Create(Task task)
		{
            if (ModelState.IsValid)
            {
                using (var db = new TeisterMaskDbContext())
                {
                    db.Tasks.Add(task);
                    db.SaveChanges();
                    return Redirect("/");
                }
            }
            return View();
        }

		[HttpGet]
		[Route("edit/{id}")]
        public ActionResult Edit(int id)
		{
            using (var db = new TeisterMaskDbContext())
            {
                var task = db.Tasks.Find(id);
                if (task != null)
                {
                    return View(task);
                }
            }
            return Redirect("/");
        }

		[HttpPost]
		[Route("edit/{id}")]
        [ValidateAntiForgeryToken]
		public ActionResult EditConfirm(int id, Task taskModel)
		{
            if (!ModelState.IsValid)
            {
                return View(taskModel);
            }

            using (var db = new TeisterMaskDbContext())
            {
                var taskFromDb = db.Tasks.Find(taskModel.Id);
                if (taskFromDb != null)
                {
                    taskFromDb.Title = taskModel.Title;
                    taskFromDb.Status = taskModel.Status;
                    db.SaveChanges();
                }
            }
            return Redirect("/");
        }
	}
}

Software Technologies/C#/ToDoList/TeisterMask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>TeisterMask</title>
	@Styles.Render("~/Content/index-style.css")
	@Styles.Render("~/Content/form-style.css")
</head>
<body>
	@RenderBody()
</body>
</html>

Software Technologies/C#/ToDoList/TeisterMask/Views/Task/Create.cshtml
@model TeisterMask.Models.Task

@{
    ViewBag.Title = "Create";
}

<header>
	<h3>Create New Task</h3>
</header>

@using (Html.BeginForm("Create", "Task", FormMethod.Post))
{
	@Html.AntiForgeryToken()

	<div>
		<label class="desc" for="title">Title</label>
		<div>
			<input id="title" name="title" type="text" class="field text fn" value="" size="8" tabindex="1" autofocus>
		</div>
	</div>

	<div>
		<fieldset>
			<legend id="title5" class="desc">
				Status
			</legend>

			<div>
				<div>
					<input id="status1" name="status" type="radio" value="Open" tabindex="2" checked>
					<label class="choice" for="status1">Open</label>
				</div>
				<div>
					<input id="status2" name="status" type="radio" value="In Progress" tabindex="3">
					<label class="choice" for="status2">In Progress</label>
				</div>
				<div>
					<input id="status3" name="status" type="radio" value="Finished" tabindex="4">
					<label class="choice" for="status3">Finished</label>
				</div>
			</div>
		</fieldset>
	</div>

	<div>
		<div>
			<input class="button" type="submit" value="Submit">
			<a class="button cancel" href="/">Cancel</a>
		</div>
	</div>
}

Software Technologies/C#/ToDoList/TeisterMask/Views/Task/Edit.cshtml
@model TeisterMask.Models.Task

@{
	ViewBag.Title = "Edit Task";
}

<header>
	<h3>Edit Task</h3>
</header>

@using (Html.BeginForm("Edit", "Task", FormMethod.Post))
{
	@Html.AntiForgeryToken()

	<div>
		<label class="desc" for="title">Title</label>
		<div>
			<input id="title" name="title" type="text" class="field text fn" value="@Model.Title" size="8" tabindex="1" autofocus>
		</div>
	</div>

	<div>
		<fieldset>
			<legend id="title5" class="desc">
				Status
			</legend>

			<div>
				<div>
					<input id="status1" name="status" type="radio" value="Open" tabindex="2" @(Model.Status == "Open" ? "checked" : "")>
					<label class="choice" for="status1">Open</label>
				</div>
				<div>
					<input id="status2" name="status" type="radio" value="In Progress" tabindex="3" @(Model.Status == "In Progress" ? "checked" : "")>
					<label class="choice" for="status2">In Progress</label>
				</div>
				<div>
					<input id="status3" name="status" type="radio" value="Finished" tabindex="4" @(Model.Status == "Finished" ? "checked" : "")>
					<label class="choice" for="status3">Finished</label>
				</div>
			</div>
		</fieldset>
	</div>

	<div>
		<div>
			<input class="button" type="submit" value="Submit">
			<a class="button cancel" href="/">Cancel</a>
		</div>
	</div>
}

Software Technologies/C#/ToDoList/TeisterMask/Views/Task/Index.cshtml
@model List<TeisterMask.Models.Task>

@{
	ViewBag.Title = "Index";
}

<div class="container">
	@Html.ActionLink("Create New Task", "Create", "Task", null, new { @class = "button" })
</div>

<div class="tasks container">
	<header>
		<div class="column header open">Open</div>
		<div class="column header inProgress">In progress</div>
		<div class="column header finished">Finished</div>
	</header>
	<ul class="column open">
		@foreach (var task in Model.Where(t => t.Status == "Open").ToList())
		{
			<li>
				@task.Title
				@Html.ActionLink(" ", "Edit", "Task", new { id = task.Id}, new { @class = "icon edit" })
			</li>
		}
	</ul>
	<ul class="column inProgress">
		@foreach (var task in Model.Where(t => t.Status == "In Progress").ToList())
		{
			<li>
				@task.Title
				@Html.ActionLink(" ", "Edit", "Task", new { id = task.Id }, new { @class = "icon edit" })
			</li>
		}
	</ul>
	<ul class="column finished">
		@foreach (var task in Model.Where(t => t.Status == "Finished").ToList())
		{
			<li>
				@task.Title
				@Html.ActionLink(" ", "Edit", "Task", new { id = task.Id }, new { @class = "icon edit" })
			</li>
		}
	</ul>
</div>